<?xml version="1.0"?>
<package format="3">
  <name>deskpet_control</name>
  <version>0.1.0</version>
  <description>Semantic action primitives to cmd_vel for the deskpet project</description>
  <maintainer email="liuzhili86@gmail.com">Liu Zhili</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>deskpet_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
